# Generated by Django 5.2.1 on 2025-05-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(choices=[('1', 'Dubai'), ('2', 'Maldives'), ('3', 'Bali'), ('3', 'India'), ('3', 'Australia'), ('3', 'Thailand')], max_length=1),
        ),
    ]
